const DEFAULT_DOWNLOAD_FORMAT = 'csv'
const FALLBACK_FILENAME_PREFIX = 'yt_'
const STREAM_ENCODING_TEXT = 'utf-8'
const STREAM_ENCODING_BASE64 = 'base64'
const FORMAT_QUERY_PARAM = 'format'
const STREAM_IDLE_TIMEOUT_SECONDS = 120
const SERVER_PORT = Number(process.env.PORT) || 3000

export {
  DEFAULT_DOWNLOAD_FORMAT,
  FALLBACK_FILENAME_PREFIX,
  STREAM_ENCODING_TEXT,
  STREAM_ENCODING_BASE64,
  FORMAT_QUERY_PARAM,
  STREAM_IDLE_TIMEOUT_SECONDS,
  SERVER_PORT,
}
